#!/usr/bin/env python2
# -*- coding: utf-8 -*-
'''
Preference class for PyAACGUI2.
2014.2.24
'''

import os

import wx
import wx.xrc as xrc

import i
import q

__author__ = 'Joker Qyou'


class PrefFrame(wx.Frame):
    '''
    Preference frame class
    '''
    def __init__(self):
        '''
        Init function
        '''
        # Load XRC layout of preference frame
        resource = xrc.XmlResource(i.APP_PREF_LAYOUT_FILE)
        pre = wx.PreFrame()
        pre = resource.LoadFrame(None, 'preference')
        self.PostCreate(pre)

        # Read option values from config file
        C = wx.GetApp().CONFIG
        bitrate = C.ReadInt(
            i.APP_CONFIG_BITRATE_KEY, 
            i.AAC_DEFAULT_BITRATE
            ) / 1000
        debug = C.ReadBool(
            i.APP_CONFIG_DEBUG_KEY, 
            i.APP_DEBUG
            )
        delorigin = C.ReadBool(
            i.APP_CONFIG_DELORIGIN_KEY, 
            i.APP_DEFAULT_DELORIGIN
            )
        
        # Bind event handlers
        self.Bind(
            wx.EVT_BUTTON, 
            self.OnPrefCancel, 
            id = xrc.XRCID('btncancel')
            )
        self.Bind(
            wx.EVT_BUTTON, 
            self.OnPrefSave, 
            id = xrc.XRCID('btnokay')
            )

        # Set values for controls
        xrc.XRCCTRL(self, 'bitratespin').SetValue(bitrate)
        xrc.XRCCTRL(self, 'debugcheck').SetValue(debug)
        xrc.XRCCTRL(self, 'delorigincheck').SetValue(delorigin)

    def OnPrefCancel(self, event):
        '''
        Handler for event generated by hitting the `Cancel ` button.
        '''
        self.Show(False)

    def OnPrefSave(self, event):
        '''
        Handler for event generated by hitting the `Okay ` button.
        '''
        # Write option values to config file
        C = wx.GetApp().CONFIG
        C.WriteInt(
            i.APP_CONFIG_BITRATE_KEY, 
            xrc.XRCCTRL(self, 'bitratespin').GetValue() * 1000
            )
        C.WriteBool(
            i.APP_CONFIG_DEBUG_KEY, 
            xrc.XRCCTRL(self, 'debugcheck').GetValue()
            )
        C.WriteBool(
            i.APP_CONFIG_DELORIGIN_KEY, 
            xrc.XRCCTRL(self, 'delorigincheck').GetValue()
            )
        # Without this line to force flush, the new config option values 
        # will be lost. 
        C.Flush()

        # Hide preference dialog
        self.Show(False)
